### ISSUE TITLE
Integrate cypress tests with CI

### ISSUE THREAD

**Issue by dicarlo2** [neo-one-suite/neo-one#1448]

**Comment by dicarlo2** [comment]
```
  - &e2e10
    working_directory: ~/neo-one
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: E2E
          command: yarn test:cypress
    parallelism: 2  
```
